### PR TITLE
Add zh-CN locale

### PR DESCRIPTION
**Pull request by EuropeJing**
This is my translation of the language file. Language is simplified Chinese. See if you have any help.

### CODE REVIEW

**Comment by liach** [comment]
个人认为全角标点更好

**Comment by liach** [comment]
Moreover, it seems you shouldn't submit it here...

**Comment by EuropeJing** [comment]
标点用全角好吗。语言的话我和bloodmc说过，他叫我上传gist.github.com. 我找不到原来有语言文件夹只能自己创建一个了。

**Comment by EuropeJing** [comment]
I can not find the original language folder can only create one of their own.

**Comment by liach** [comment]
赞一个，有总比没有好

**Comment by EuropeJing** [comment]
恩，也当方便下大家了

**Comment by bloodmc** [comment]
@EuropeJing Can you update PR for latest update?

Thanks

**Comment by EuropeJing** [comment]
@bloodmc sure.I'll make it.

**Comment by EuropeJing** [comment]
@bloodmc It has been updated now
Apply to Version 4.0.0

**Comment by bloodmc** [comment]
@EuropeJing Please update again =)

**Comment by EuropeJing** [comment]
@bloodmc Griefprevention - MC 1.10.2 v4.0.0.325 (Including v4.0.0.322) An error occurred
[griefprevention/sponge]: Unable to initialize plugin. Detected SpongeForge build 2464 but GriefPrevention requires build 2497+.
But the latest SpongeForge is 1.10.2-2281-5.2.0-BETA-2464

**Comment by bloodmc** [comment]
http://files.minecraftforge.net/spongepowered

**Comment by EuropeJing** [comment]
Well, it has been updated

**Comment by bloodmc** [comment]
@EuropeJing Thanks i'll work on this soon. I'll be adding a config option to load the respective locale.

**Comment by bloodmc** [comment]
Added in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/f0aea6303a3a392fc039e2ca2875873f346748bb

Thanks

**Pull request closed without merging**
