### PR TITLE
Fix for java.lang.OutOfMemoryError: unable to create new native thread

### PR DESCRIPTION
**Pull request by KaiKikuchi**
Hello,
[this code](https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/GPPlayerData.java#L222) is causing [this issue](https://pastebin.com/GEnkchFY), crashing the server on startup because there are too many threads and the JVM cannot create more threads.

This issue is happening on a highly populated server.

The executor is used improperly: executors should run multiple threads, managing how many threads should concurrently run. 

This commit changes the use of one executor per thread to one executor for all threads while loading players data.

This has been tested and fixes the issue.

### CODE REVIEW

**Comment by Zidane** [comment]
@KaiKikuchi 

This seems like a case where it would be best to submit a PR to SpongeAPi to add the ability to have this functionality (as that would let this plugin continue to operate within Sponge's systems here instead of outside it).

**Comment by bloodmc** [comment]
@KaiKikuchi Instead of creating a single thread executor, try to create a single sponge executor service and see if that solves it. If so, update your PR with the changes.

Sponge doesn't allow its executor service to be shut down which was probably causing the leaks.

**Comment by KaiKikuchi** [comment]
Thank you for your attention.

@Zidane Are you talking about having a single thread asynchronous executor?

@bloodmc That won't solve the issue as SpongeAPI 5.1 does not provide a way to create a single thread sponge executor service.

If I am missing something, please let me know.

Also feel free to add commits to this pull request if you want. Also you can close it and fix it your own way. I just wanted to provide a working way to fix this issue.


References:
- https://jd.spongepowered.org/5.1.0/org/spongepowered/api/scheduler/Scheduler.html#createAsyncExecutor-java.lang.Object-
- https://github.com/SpongePowered/SpongeCommon/blob/2178bf4508669514595116157b07c880f02ea1cd/src/main/java/org/spongepowered/common/scheduler/AsyncScheduler.java#L47

**Comment by bloodmc** [comment]
@KaiKikuchi I know, I'm saying to call sponge's createAsyncExecutor once and store it for continued use to see if it fixes the issue.

**Comment by KaiKikuchi** [comment]
I tried that before using the java single thread executor and it didn't fix the issue. It still was creating too many threads. I used VisualVM to troubleshoot the issue.

**Comment by bloodmc** [comment]
@KaiKikuchi Please fix the formatting for PR. Imports/spacing were changed. GP uses same formatting as Sponge.

**Comment by KaiKikuchi** [comment]
As it's a 1/3 lines change, you can just say what is wrong with the formatting and how to fix it, or provide a link to the style guide (as I didn't find one quickly enough). Or just push any change to this branch.

**Comment by ryantheleach** [comment]
The only things I can notice wrong with the style are the absolute basics. tabs v spaces, and you have changed the ordering of the imports dramatically.

If it's a 3 line change, the diff should look like a 3 line change, or you have done something drastically incorrect.

**Comment by KaiKikuchi** [comment]
My IDE is set to use tabs instead of spaces by default, and it automatically changed the order of the imports. You know the needed/real changes are just 3. The "absolute basics" are actually the "absolute Sponge team style basics".

**Comment by ryantheleach** [comment]
@KaiKikuchi The "absolute basics" are the "absolute basic etiquette when committing on *anyones* external repo in order to match their styling.

I wasn't meaning to imply that your style choices or opinions were somehow wrong.

**Pull request closed without merging**
